### ISSUE TITLE
story: Add support in CP to process create request from client

### ISSUE THREAD

**Issue by littlestar642** [gopay-bootcamp/octavius#1]
#### Description

As the Control Panel (CP) should be able to process incoming create command from the client, a corresponding functionality needs to be implemented in CP so that this flow is complete. The incoming protobuf is to saved in etcd and send back the client appropriate error code.

Substories -:

- [ ] Add the CP executor function
- [ ] Add the corresponding etcd client function

#### Present Behaviour

No such behaviour present.

#### Expected Behaviour

CP should be able to process client request to create a proc.

**Comment by djChatt** [comment]
Close this issue if resolved?

**Comment by littlestar642** [comment]
Yeah. Sure!
