### ISSUE TITLE
story: storing metadata in Etcd

### ISSUE THREAD

**Issue by yashipro13** [gopay-bootcamp/octavius#10]
#### Description
The control plane on receiving protobuf from the client, given the Etcd container is up and running, control plane be able to store the metadata to Etcd without error.

#### Present Behaviour
No such behaviour

#### Expected Behaviour
The protobuf sent by client should be stored in Etcd by control plane in order of successful creation of new job.

#### Screenshots
Not applicable.

**Comment by littlestar642** [comment]
implemented in #5
