### ISSUE TITLE
story: storing audit logs in file server side

### ISSUE THREAD

**Issue by yashipro13** [gopay-bootcamp/octavius#11]
#### Description
Given any statement is executed from client end or from executor, and Etcd is up and running, the logs should be stored in Etcd without any error.

#### Present Behaviour
No such behaviour

#### Expected behaviour
The logs should be saved in Etcd on execution of all commands for tracking purpose.

#### Screenshots
Not applicable in this case.

**Comment by jasoet** [comment]
Some information that we need as audit logs.
1. The Actor (users or executor), we will need to know which user and with executor sends a request.
2. Request Parameter and Header (if available), we need to know the payload of the request.
3. .... (need to discuss more)
