### ISSUE TITLE
story: updating status of job after execution

### ISSUE THREAD

**Issue by yashipro13** [gopay-bootcamp/octavius#13]
#### Description
Given the executor sends the Job logs and status after execution, the control plane should update the status received by executor to the Etcd. The status received after execution may be `success` or `failure` or specific failure message.

#### Present Behaviour
No such behaviour.

#### Expected Behaviour
The job status should be updated correctly after execution of job by executor to the etcd. 

#### Screenshots
Not applicable in this case.

**Comment by littlestar642** [comment]
not applicable with the present dev flow hence closing
