### ISSUE TITLE
story: Add config and create command support in cli

### ISSUE THREAD

**Issue by djChatt** [gopay-bootcamp/octavius#4]
Description
Need to handle client config, client request for creating new job metadata. Create a proper proto message contract.

Substories -:

- [x] As a cli, should be able to store client config in a yaml file, so that when a request is done by the client we can read the details from the file and add it with the request for authentication and security.

- [x] As a cli, should be able to read from the metadata.json provided by the client and send it to Control Plane.

- [x] As a administrator, create a metadata-post-request proto

Present Behaviour

No such behaviour present.

Expected Behaviour

Cli should be able to handle config and create commands.

**Comment by littlestar642** [comment]
Merging #6 for now as it is needed to move ahead and expecting another PR after tests are implemented. @djChatt and @JaiminRathod

**Comment by djChatt** [comment]
Issue resolved in #24 . Closing it.
