### ISSUE TITLE
fix: client should be able to create new job

### ISSUE THREAD

**Issue by yashipro13** [gopay-bootcamp/octavius#43]
#### Description
Make sure that client is unable to create new jobs. 
In the recent change due to new error infra as in PR #39 , PostMetadata is breaking due to outdated error check.
Also ensure all outdated checks are rectified.

#### Present Behaviour
CP is throwing value not found error when client is trying to create a new job.

#### Expected Behaviour
CP should be able to save new client jobs to etcd without an error.

**Comment by littlestar642** [comment]
after #46 gets merged a this will not be an issue as such
