### ISSUE TITLE
story: each executor should know the job it is executing, and jobs that are pending

### ISSUE THREAD

**Issue by yashipro13** [gopay-bootcamp/octavius#53]
#### Description
Implement scheduler things like executor/executor-id/pending, executor/executor-id/running etcd structures to support the scheduling setup at controller end.

#### Present Behaviour
No such behaviour

#### Expected Behaviour
Running and pending jobs structures should be created at etcd end, so that job scheduler could run.

**Comment by littlestar642** [comment]
issue not relevant with updated discussion
