### ISSUE TITLE
feat: Use flag instead of parsing PATH string in cli

### ISSUE THREAD

**Issue by littlestar642** [gopay-bootcamp/octavius#7]
#### Description

When parsing job metadata client side, we are taking the PATH variable in cli and parsing the string it to get the value. Instead a cobra flag should be implemented that sets these values, instead of a default.

#### Present Behaviour

string parsing in cli for PATH variable

#### Expected Behaviour

flags should be used to parse

**Comment by djChatt** [comment]
Closing story as feature is already implemented in #24 and merged.
