### ISSUE TITLE
bug: describe and getstream command do not produce proper error message

### ISSUE THREAD

**Issue by littlestar642** [gopay-bootcamp/octavius#82]
Description:

For all the errors generated on the server we get a single message that is `error in describing job`. I would suggest in stead we should at least provide the user with proper error messages depending on the error generated for example `no value found`, `internal server error`, etc. Similarly for getstream command.

Present Behaviour:

A common error message in generated

Expected Behaviour:

Proper error messages should be generated

**Comment by yashipro13** [comment]
I am taking this up.
