### ISSUE TITLE
fix: Add validation of metadata during job creation

### ISSUE THREAD

**Issue by JaiminRathod** [gopay-bootcamp/octavius#89]
#### Description
Now we are not doing validation of metadata during job creation, so it must be done.

#### Present behaviour
No such behaviour.

#### Exepected behaviour
There should be functionality of metadata validation during job creation.

**Comment by littlestar642** [comment]
To check if a docker image is valid or not we can make a silent curl to this endpoint `https://hub.docker.com/v2/repositories/library/<image-name>/tags/<tag-name>` and check the json returned to contain a field called `images`. In case of error no such field is returned and we can tell the image is not present.

I would suggest using exec library.
