### ISSUE TITLE
fix: pull project specific functions outside Repo

### ISSUE THREAD

**Issue by yashipro13** [gopay-bootcamp/octavius#91]
#### Description
There are several project specific functions involving etcd inside repo, eg `CheckJobIsAvailable`, `ValidateJob`, `FetchNextJob` etc. This is causing same piece of logic to be rewritten again, which is not a good design practice. Move such project specific code outside to execution directory - one upper level and keep functions in repo that are only etcd and db specific. 

#### Present Behaviour
Repo has project context specific functions.

#### Expected Behaviour
As described above

#### Note
While resolving above issue consider-
Keeping all grpc errors only at the execution level. Avoid keeping grpc errors at different levels for easy maintenance and to avoid nesting of errors.

**Comment by littlestar642** [comment]
It seems like there are three packages that needs our care. Out of these three, the job package of `internal/controller/repository/jo`b has the most amount of refactoring and is equivalent to the combined `executor` and `metadata` packages. 

I would suggest we make two pairs with equal amount of resources and tackle this final task at hand.
